trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

- script: dotnet restore
  displayName: 'Restore NuGet Packages'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build Solution'

- script: dotnet test --configuration $(buildConfiguration) --no-build
  displayName: 'Run Unit Tests'
